import { NextResponse } from 'next/server';
import { Student } from '../../../types/student';
import { DataManager } from '../../../utils/dataManager';

const dataManager = DataManager.getInstance();

// GET /api/students - Get all students with optional filtering
export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const classFilter = searchParams.get('class');
    const searchQuery = searchParams.get('search');
    const typeFilter = searchParams.get('type');

    let filteredStudents = dataManager.getStudents();

    // Apply class filter
    if (classFilter && classFilter !== 'all') {
      filteredStudents = filteredStudents.filter((student: Student) => student.class === classFilter);
    }

    // Apply search filter
    if (searchQuery) {
      filteredStudents = filteredStudents.filter((student: Student) => 
        student.name.toLowerCase().includes(searchQuery.toLowerCase()) || 
        student.nis.includes(searchQuery)
      );
    }

    // Apply type filter
    if (typeFilter && typeFilter !== 'all') {
      filteredStudents = filteredStudents.filter((student: Student) => student.type === typeFilter);
    }

    return NextResponse.json({ students: filteredStudents });
  } catch (error) {
    console.error('Error in GET /api/students:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}

// POST /api/students - Add a new student
export async function POST(request: Request) {
  try {
    const body = await request.json();
    
    // Create new student object (ID will be generated by data manager)
    const newStudentData = {
      nis: body.nis,
      name: body.name,
      class: body.class,
      status: 'hadir',
      time: '-',
      photo: body.name.split(' ').map((n: string) => n[0]).join('').toUpperCase(),
      attendance: 100,
      late: 0,
      absent: 0,
      permission: 0,
      type: body.type || 'new'
    };
    
    const newStudent = dataManager.addStudent(newStudentData);
    
    return NextResponse.json({ success: true, student: newStudent }, { status: 201 });
  } catch (error) {
    console.error('Error in POST /api/students:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}