import { NextResponse } from 'next/server';
import { DataManager } from '../../../utils/dataManager';

const dataManager = DataManager.getInstance();

// GET /api/teachers - Get all teachers with their schedules
export async function GET() {
  try {
    const teachers = dataManager.getTeachers();
    return NextResponse.json({ teachers });
  } catch (error) {
    console.error('Error in GET /api/teachers:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}

// POST /api/teachers - Add a new teacher
export async function POST(request: Request) {
  try {
    const body = await request.json();
    
    // Create new teacher object (ID will be generated by data manager)
    const newTeacherData = {
      name: body.name,
      subject: body.subject,
      photo: body.name.split(' ').map((n: string) => n[0]).join('').toUpperCase(),
      schedule: body.schedule || []
    };
    
    const newTeacher = dataManager.addTeacher(newTeacherData);
    
    return NextResponse.json({ success: true, teacher: newTeacher }, { status: 201 });
  } catch (error) {
    console.error('Error in POST /api/teachers:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}